﻿//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------
namespace ModuleWorkFlow
{
    public partial class ExceptionReview
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.LinkButton lnk_view;
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_save;
        protected global::System.Web.UI.WebControls.Label Label_KdCode;
        protected global::System.Web.UI.WebControls.TextBox txt_KdCode;
        protected global::System.Web.UI.WebControls.CheckBox chk_Processed;
        protected global::System.Web.UI.WebControls.LinkButton lnk_search;
        protected global::System.Web.UI.WebControls.GridView gvExceptions;
        protected global::System.Web.UI.WebControls.Label Label_Message;
    }
}