//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     直接修改此文件可能导致不可预期的行为，并且在重新生成时丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleWorkFlow
{
    public partial class GSPartMasterList
    {
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_edit;

        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_search;

        protected global::System.Web.UI.WebControls.Label Label_JHSPartNo;

        protected global::System.Web.UI.WebControls.TextBox TextBox_JHSPartNo;

        protected global::System.Web.UI.WebControls.Label Label_CustomerMaterialNo;

        protected global::System.Web.UI.WebControls.TextBox TextBox_CustomerMaterialNo;

        protected global::System.Web.UI.WebControls.DataGrid MainDataGrid;

        protected global::System.Web.UI.WebControls.Label Label2;

        protected global::System.Web.UI.WebControls.Label Label_Message;
    }
}
