//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleWorkFlow
{
    public partial class GSPartMasterUpload
    {
        protected global::System.Web.UI.WebControls.LinkButton lnk_view;
        protected global::System.Web.UI.WebControls.Label Label_CustomerAbbr;
        protected global::System.Web.UI.WebControls.TextBox txt_CustomerAbbr;
        protected global::System.Web.UI.WebControls.FileUpload FileUploadPartMaster;
        protected global::System.Web.UI.WebControls.Label Label_FileName;
        protected global::System.Web.UI.WebControls.Button btn_select;
        protected global::System.Web.UI.WebControls.Button btn_upload;
        protected global::System.Web.UI.WebControls.Label Label_Message;
    }
}
