//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleWorkFlow
{
    public partial class LabelBindingRecordList
    {
        protected global::System.Web.UI.WebControls.Label Label_CustomerProductNo;
        protected global::System.Web.UI.WebControls.TextBox TextBox_CustomerProductNo;
        protected global::System.Web.UI.WebControls.Label Label_ProductNo;
        protected global::System.Web.UI.WebControls.TextBox TextBox_ProductNo;
        protected global::System.Web.UI.WebControls.Label Label_StartTime;
        protected global::System.Web.UI.WebControls.TextBox TextBox_StartTime;
        protected global::System.Web.UI.WebControls.Label Label_EndTime;
        protected global::System.Web.UI.WebControls.TextBox TextBox_EndTime;
        protected global::System.Web.UI.WebControls.Button Button_Search;
        protected global::System.Web.UI.WebControls.DataGrid MainDataGrid;
        protected global::System.Web.UI.WebControls.Label Label_Message;
    }
}
