//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleWorkFlow
{
    public partial class PackingList
    {
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_edit;
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_search;
        protected global::System.Web.UI.WebControls.TextBox TextBox_KDQRCode;
        protected global::System.Web.UI.WebControls.TextBox TextBox_PartNo;
        protected global::System.Web.UI.WebControls.TextBox TextBox_PartCode;
        protected global::System.Web.UI.WebControls.DataGrid MainDataGrid;
        protected global::System.Web.UI.WebControls.Label Label_Message;
    }
}
