//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------
namespace ModuleWorkFlow
{
    public partial class PackingExceptionList
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.LinkButton lnk_search;
        protected global::System.Web.UI.WebControls.Label Label_KdCode;
        protected global::System.Web.UI.WebControls.TextBox txt_KdCode;
        protected global::System.Web.UI.WebControls.Label Label_PartNo;
        protected global::System.Web.UI.WebControls.TextBox txt_PartNo;
        protected global::System.Web.UI.WebControls.Label Label_DateFrom;
        protected global::System.Web.UI.WebControls.TextBox txt_DateFrom;
        protected global::System.Web.UI.WebControls.Label Label_DateTo;
        protected global::System.Web.UI.WebControls.TextBox txt_DateTo;
        protected global::System.Web.UI.WebControls.CheckBox chk_Processed;
        protected global::System.Web.UI.WebControls.GridView gvExceptions;
        protected global::System.Web.UI.WebControls.Label Label_Message;
    }
}
