//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace ModuleWorkFlow
{
    public partial class PrintRecordList
    {
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_search;
        protected global::System.Web.UI.WebControls.TextBox TextBox_SupplyBatchNo;
        protected global::System.Web.UI.WebControls.TextBox TextBox_PartNo;
        protected global::System.Web.UI.WebControls.TextBox TextBox_CartonNo;
        protected global::System.Web.UI.WebControls.TextBox TextBox_PrintType;
        protected global::System.Web.UI.WebControls.DataGrid MainDataGrid;
        protected global::System.Web.UI.WebControls.Label Label2;
        protected global::System.Web.UI.WebControls.Label Label_Message;
    }
}
