//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleWorkFlow
{
    public partial class ShippingGoodsREPrintList
    {
        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_search;

        protected global::System.Web.UI.WebControls.LinkButton lnkbutton_print;

        protected global::System.Web.UI.WebControls.TextBox TextBox_PartNo;

        protected global::System.Web.UI.WebControls.TextBox TextBox_PartName;

        protected global::System.Web.UI.WebControls.TextBox TextBox_SupplyBatchNo;

        protected global::System.Web.UI.WebControls.DropDownList DropDownList_PrinterName;

        protected global::System.Web.UI.WebControls.CheckBox CheckBox_ShowAll;

        protected global::System.Web.UI.WebControls.DataGrid MainDataGrid;

        protected global::System.Web.UI.WebControls.Label Label2;

        protected global::System.Web.UI.WebControls.Label Label_Message;

        protected global::System.Web.UI.WebControls.HiddenField hid_ClientId;
    }
}
