<%@ Page Language="c#" CodeBehind="GSPartMasterUpload.aspx.cs" AutoEventWireup="false" Inherits="ModuleWorkFlow.GSPartMasterUpload" MasterPageFile="~/DefaultSub.Master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="contentHolder" runat="server">
    <div id="Wrapper"><div id="Header"><div class="headbox"><div class="linebox"><a href="#">&#26631;&#31614;&#31649;&#29702;</a><img src="images/arrow.png" /><a href="#"><%=menuname %></a></div><div class="logout"><a href="login.aspx" target="_parent">&#30331;&#20986;</a></div><div class="clearbox"></div></div></div>
    <div id="Container"><div id="Content"><div id="Menu"><div class="menubox"><div class="mod1"><ul><li class="btn5"><asp:LinkButton ID="lnk_view" runat="server" OnClick="lnk_view_Click">&#36820;&#22238;</asp:LinkButton></li></ul></div><div class="clearbox"></div></div></div>
    <div class="container mt-3 border border-primary"><div class="container mt-3 mb-3">
        <asp:FileUpload ID="FileUploadPartMaster" runat="server" Style="display:none" />
        <div id="gsPartMasterDropArea" class="gs-part-master-drop border border-primary text-center"><div class="gs-part-master-title">&#25302;&#25289;&#20809;&#26495;&#26631;&#31614;&#25972;&#29702; Excel &#21040;&#36825;&#37324;</div><div class="gs-part-master-subtitle">&#25110;&#28857;&#20987;&#36873;&#25321; Excel &#25991;&#20214;</div><asp:Label ID="Label_FileName" runat="server" CssClass="gs-part-master-file"></asp:Label></div>
        <div class="mt-3 d-flex"><asp:Button ID="btn_select" runat="server" Text="&#36873;&#25321;&#25991;&#20214;" CssClass="btn btn-outline-primary me-10" OnClientClick="openGSPartMasterFile(); return false;" /><asp:Button ID="btn_upload" runat="server" Text="&#19978;&#20256;" CssClass="btn btn-primary" OnClick="btn_upload_Click" /></div>
    </div></div>
    <div class="container mt-3 border border-warning"><table width="100%" align="center" class="tbMessage"><tr valign="middle"><td width="10%" height="28"><div align="center"><b>&#25552;&#31034;</b></div></td><td class="msg" width="85%">&nbsp;&nbsp;<asp:Label ID="Label_Message" runat="server"></asp:Label></td></tr></table></div>
    </div></div></div>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="JSHolder" runat="server">
<style type="text/css">.gs-part-master-drop{min-height:180px;padding:42px 20px;background:#f8fbff;cursor:pointer}.gs-part-master-drop.dragover{background:#eaf3ff;border-style:dashed!important}.gs-part-master-title{font-size:18px;font-weight:600;color:#0d6efd}.gs-part-master-subtitle{margin-top:8px;color:#666}.gs-part-master-file{display:block;margin-top:14px;color:#333}</style>
<script type="text/javascript">function openGSPartMasterFile(){document.getElementById('<%=FileUploadPartMaster.ClientID%>').click()}(function(){var d=document.getElementById('gsPartMasterDropArea'),i=document.getElementById('<%=FileUploadPartMaster.ClientID%>'),l=document.getElementById('<%=Label_FileName.ClientID%>');function s(f){if(!f||!f.length)return;var t=new DataTransfer;t.items.add(f[0]);i.files=t.files;l.innerText=f[0].name}d.addEventListener('click',openGSPartMasterFile);i.addEventListener('change',function(){s(i.files)});d.addEventListener('dragover',function(e){e.preventDefault();d.classList.add('dragover')});d.addEventListener('dragleave',function(){d.classList.remove('dragover')});d.addEventListener('drop',function(e){e.preventDefault();d.classList.remove('dragover');s(e.dataTransfer.files)})})();</script>
</asp:Content>
